### PR TITLE
refactor(cli): remove duplicate code

### PR DESCRIPTION
**Pull request by alan-agius4**
This code is duplicate

https://github.com/alan-agius4/compodoc/blob/eb25e1a5fe4650e69f3b2e90c66a1280ee217ccf/src/index-cli.ts#L97

https://github.com/alan-agius4/compodoc/blob/eb25e1a5fe4650e69f3b2e90c66a1280ee217ccf/src/index-cli.ts#L101

### CODE REVIEW

**Comment by vogloblinsky** [comment]
Sorry but --includes gives the path of external markdown files, & --includesName the name of item menu of externals markdown files
Two different configuration entries.

**Comment by alan-agius4** [comment]
I know, but they are duplicate.  Check lines 97, 101, 129, 133

**Comment by vogloblinsky** [comment]
Ok sorry, can you use develop branch for the PR ?

**Comment by alan-agius4** [comment]
Done

**Comment by vogloblinsky** [comment]
Thanks for the PR

**Pull request merged**
