### PR TITLE
style(compodoc): use pointer for links

### PR DESCRIPTION
**Pull request by Sibiraj-S**
* use `cursor: pointer` for links

### CODE REVIEW

**Comment by vogloblinsky** [comment]
It is not the default behavior on major browsers ?

**Comment by Sibiraj-S** [comment]
Nope. Some have, some doesn't. Hence the consistency

**Comment by Sibiraj-S** [comment]
Closed by mistake :sweat_smile:

**Comment by Sibiraj-S** [comment]
This PR is not needed if `bootstrap` is updated to v4 #493

**Pull request closed without merging**
