### PR TITLE
refactor: prepareExternalIncludes parses children recursively

### PR DESCRIPTION
**Pull request by jabiinfante**
Right now, only 2 levels of depth are supported.

I have had to refactor a little bit the _prepareExternalIncludes_ method, and have decided to limit in *5* levels of depth (which applies across the application, allthought it only affects on the "--includes" folder (I think).

I have added a logger.error whenever someone tries to set more than 5 levels of depth on a summary.json file.

### CODE REVIEW

**Comment by vogloblinsky** [comment]
Hi,

Thanks for this great addition.

**Comment by jabiinfante** [comment]
happy to help.
thank you for this really usefull piece of software ;)

**Comment by vogloblinsky** [comment]
> thank you for this really usefull piece of software ;)

I try, there are several features to add to make it "perfect" :smile:

**Comment by vogloblinsky** [comment]
There is an issue for e2e test : the variable `currentDepth` is not defined in `search.js`
Can you fix it ?
Thanks

**Comment by jabiinfante** [comment]
ups... I got it fixed, but i think you should open this pull request, right?
Or should i just open another PR?

**Comment by vogloblinsky** [comment]
no just send me the fix here i will update the code directly

**Comment by vogloblinsky** [comment]
thanks

**Comment by jabiinfante** [comment]
Here it is:
https://github.com/jabiinfante/compodoc/commit/d3fe7149dbed2cd3395a9bedd9d2f27a5e04235f

**Pull request merged**
