### PR TITLE
fix: exclude internal members from generated documentation

### PR DESCRIPTION
**Pull request by mattlewis92**
Made the last one against the wrong branch 😃

### CODE REVIEW

**Comment by vogloblinsky** [comment]
thanks Matt 👌🏻, i check that tonight.

**Comment by vogloblinsky** [comment]
Matt, did you have a code example for this "exclusion" please ? It is for README details

**Comment by mattlewis92** [comment]
Sure thing. 

```
class Foo {

  /**
   * @internal
   */
  bar() {} // not included in the docs

  bam() {} // included in the docs

}
```

I borrowed the idea from [typedoc](https://github.com/TypeStrong/typedoc). They also allow `@hidden` and `@private` - what do you think about excluding methods marked with these as well?

**Comment by vogloblinsky** [comment]
> I borrowed the idea from typedoc. They also allow @hidden and @private - what do you think about excluding methods marked with these as well?

Yes it could be fine. Could you add a little test for all that stuff, just like this : [TEST](https://github.com/compodoc/compodoc/blob/master/test/src/cli.spec.ts#L359)

**Comment by mattlewis92** [comment]
Ah I was wondering about the best way of writing a test, will add one tomorrow, as well as for the other PR I just sent 😄

**Comment by mattlewis92** [comment]
@vogloblinsky I've added some tests for this + for the other PR (and fixed a few bugs they found! 😄 ) LMK if you'd like me to change anything else

**Comment by vogloblinsky** [comment]
Thanks Matt, feel free to add 2 others issues for your 2 last TODOS (https://github.com/mattlewis92/angular-calendar/issues/125)

The others TODOS are here 😄  : https://github.com/compodoc/compodoc/issues/46

**Comment by mattlewis92** [comment]
Done, will send you some PRs for them both over the next few days 😃

**Comment by vogloblinsky** [comment]
Thanks. I am focusing on routes page right now.

**Pull request merged**
