### PR TITLE
perf(fs): Directory tree parsing optimization

### PR DESCRIPTION
**Pull request by impy88**
Hello, 

First of all, I appreciate your great product and I do really want to participate in it. 

I'm facing a performance hit using Compodoc in our product with lots of components and sub-packages. I propose to reduce the parsing directory tree multiple times and use the slow `glob` package to compare every single item.

Here are some numbers we have:
* Version of compodoc: `1.1.16`
* NodeJS version: `14.18.0`
* Number of TS files: `55817`
* Command: `compodoc -p tsconfig.json -d library -e json`
* TSConfig file ignores all the specs, mocks, and fixtures. 

The time it takes to run:
- *Without* the change: 5 min 51 seconds
- *With* the change: 52 seconds

What I did: 
- Replaced `findit2` and `glob` dependencies with `fast-glob`
- Removed unused `parser.util.class.ts` file
- Replaced internal functions for folder ignoring patterns consumed by `fast-glob`
- Optimized the code to consume `cwd` from the first argument
- Added default ignore patterns

### CODE REVIEW

**Comment by vogloblinsky** [comment]
Hi Maxim,

Thanks for this great PR !

I just activate and run CI for this PR. Did you have 5' to fix the issue ?

Thanks

**Comment by impy88** [comment]
> Hi Maxim,
> 
> Thanks for this great PR !
> 
> I just activate and run CI for this PR. Did you have 5' to fix the issue ?
> 
> Thanks

Hey, 

sure, I just fixed the issue on `scan-files.ts`. Seems to be good now :)

**Comment by impy88** [comment]
Hi @vogloblinsky ,

can we get this PR merged? I don't see any problems in tests so far apart from the fact that some tokens are missing from the CI end (like the sonar token) which seems to me not related to the change.

**Comment by impy88** [comment]
Hi @vogloblinsky ,

I know you might be busy and this is just a friendly ping :) 

I see that another PR not related to change is failing here for the same reason. https://github.com/compodoc/compodoc/runs/6019188699?check_suite_focus=true 

Can we check what can be done to get the PR merged or how can I help in order to proceed? 

/Max

**Comment by vogloblinsky** [comment]
Yes, there is an issue with a test repository. I will look that asap.

**Comment by impy88** [comment]
@vogloblinsky Hi there, hope you are doing good! Any thoughts about the PR, maybe I can help on this somehow?  I'd say:  don't hesitate to ask

**Comment by vogloblinsky** [comment]
Hi, no, i need to quickly find some time to fix an issue with a sample test project that raised with the CI on your PR, not related to your code ;)

**Comment by impy88** [comment]
Hi @vogloblinsky 

just a friendly ping as I do not fully agree with the stale bot :) Any idea about that issue?

**Comment by impy88** [comment]
Hi @vogloblinsky, hope you are doing well! Do you think that we can progress on that change? I would be happy to provide any help needed

**Comment by impy88** [comment]
Hi @vogloblinsky , just a friendly ping. Any updates?

**Comment by impy88** [comment]
Don't close please, we are still pending for updates

**Comment by vogloblinsky** [comment]
Due to conflict in files and no way to resolve it in local, i copy-pasted your fixes in https://github.com/compodoc/compodoc/commit/332722a1c9afb660844dc5d1d159175a8b2f68e5
Thanks for the PR

**Pull request closed without merging**
