### PR TITLE
feat(app): add unit test coverage summary page

### PR DESCRIPTION
**Pull request by bhofmei**

### CODE REVIEW

**Comment by vogloblinsky** [comment]
Thanks a lot for this PR @bhofmei !
Could you add a unit test for that ?
Just generate an istanbul JSON coverage for `test/src/todomvc-ng2` and run one test like one inside `test/src/cli`
Thanks

**Comment by bhofmei** [comment]
From what I can tell, `test/src/todomvc-ng2` doesn't have any unit tests itself to run and get coverage for. Did I just miss them? Or am I supposed to write those unit tests as well? If the later, I'm fairly new to angular and I'm unfamiliar with the framework you are using for testing. I've been using karma.

**Comment by vogloblinsky** [comment]
If you prefer, take 4-5 files from the project you use to generate the screenshot here : https://github.com/compodoc/compodoc/issues/440#issuecomment-398815897
Create a new folder inside `test/src/xxx`
Put the files in it, with the JSON istanbul coverage file.
Run compodoc with all this setup. ok for you ?
The idea for the unit test of compodoc is to test the output for a combinaison of file and flags.
We only want to test the process of Compodoc, not running unit testing of the `test/src/xxx` folder and after run compodoc.

**Comment by vogloblinsky** [comment]
Hi @bhofmei any news ?

**Comment by bhofmei** [comment]
Sorry! I was on vacation then when I got back I had a bunch of stuff to do for other projects. I’ll work on this now and hopefully finish it up in the next few days.

**Comment by vogloblinsky** [comment]
Cool thanks !

**Comment by bhofmei** [comment]
Just an update. I haven't forgotten about this! I've been working on it but whenever I run the tests locally, it fails and the test it fails on keeps changing, so I've been trying to figure that out.

**Comment by vogloblinsky** [comment]
If the test is not related to your PR main code and feature, don't waste time on it. I will look that after merging it.

**Comment by bhofmei** [comment]
Done!

**Pull request merged**
