### PR TITLE
Feature/update several deps

### PR DESCRIPTION
**Pull request by alan-agius4**
Updated several dependencies:
- `ts-simple-ast` from `6.12.0` to `8.1.0`

### CODE REVIEW

**Comment by vogloblinsky** [comment]
Thanks, could you keep live-server on 1.1.0 due to this ? https://github.com/compodoc/compodoc/issues/232#issuecomment-316685443

**Comment by alan-agius4** [comment]
Yeah sure, and I need to check why some tests are failing. Like the custom avatar one etc.

**Comment by alan-agius4** [comment]
I had a look at `live-server` version `1.2.0` and it does specify `send` as dependency.

**Comment by alan-agius4** [comment]
I also noticed that when there is a TypeScript error within the code and you run ``npm run build` errors are not being emitted.

**Pull request closed without merging**
