### PR TITLE
fix(UI): a few issues with the src on customLogo img

### PR DESCRIPTION
**Pull request by feldmanz66**
## This PR addresses two fixes with the custom logo:

* Currently the customLogo breaks the app. The new customLogo img has an attribute data-type="compodoc-logo".  Within the app this attribute is queried for so that a prefix can be added to the data-src. The code is written such that if it has the `data-type` then it needs a `data-src` because it grabs this object and it can't be null. This fix changes the `src` attribute to `data-src`.
* Currently the customLogo only handles a png type for an image. This has been updated to accept all extensions as we have a need for svg extension

### CODE REVIEW

**Comment by feldmanz66** [comment]
For some reason the logo is not loading, looking into this

**Comment by feldmanz66** [comment]
Any chance we can get this merged? @vogloblinsky

**Comment by vogloblinsky** [comment]
Yes, can you had a test if a user didn't supply a custom logo ?
Thanks

**Comment by vogloblinsky** [comment]
Any news @feldmanz66 ?

**Comment by feldmanz66** [comment]
I will write the tests this week! Lost track in time

**Comment by feldmanz66** [comment]
@vogloblinsky added a unit test

**Comment by feldmanz66** [comment]
@vogloblinsky bump any way we can get this merged into a release

**Pull request merged**
