### PR TITLE
fix(app): Fix enum member types parsing

### PR DESCRIPTION
**Pull request by pawtwa**
Fix matching the default value and radio options for any @Input() of enum type

### CODE REVIEW

**Comment by pawtwa** [comment]
@vogloblinsky here is the another case

**Comment by vogloblinsky** [comment]
Could you add a integration test please ?

**Comment by pawtwa** [comment]
Oki, I will, a little bit later

**Comment by vogloblinsky** [comment]
Thanks

**Comment by pawtwa** [comment]
I am back, I gonna write the test @vogloblinsky

**Comment by pawtwa** [comment]
@vogloblinsky I have just pushed the changes

**Comment by vogloblinsky** [comment]
Thanks for the test and the PR

**Comment by pawtwa** [comment]
@vogloblinsky thanks for accepting the PR

**Pull request merged**
