### PR TITLE
Add raw descriptions

### LINKED ISSUE #909: [BUG] JSON output missing "rawdescription" on several types
##### **Overview of the issue**

When outputting to JSON, I noticed that the following types are missing a `rawdescription` field:

* pipes
* interfaces
* injectables
* directives
* modules (not important for my usecase)
* miscellaneous (not important for my usecase)

##### **Motivation for or Use Case**

I'm working on a custom integration with [StorybookJS](https://github.com/storybookjs/storybook). For displaying documentation, the library will parse raw markdown from the JSDoc. I need access to the raw markdown for the types listed above, _not_ the HTML-safe description field, to avoid encoding issues.

##### **Reproduce the error**

Create Compodoc JSON output for the types listed above.

##### **Related issues**

#875 

##### **Suggest a Fix**

Add the properties to the necessary fields in `angular-dependencies.ts`.

### PR DESCRIPTION
**Pull request by jlutz777**
Closes #909

### CODE REVIEW

**Comment by jlutz777** [comment]
I believe these failures were not a result of my change, but if I need to make changes, please let me know.

**Comment by jlutz777** [comment]
Please let me know what needs done to get this merged.

**Comment by jlutz777** [comment]
I'm still interested in this if someone wanted to give me any feedback.

**Comment by manekinekko** [comment]
Hey @jlutz777 thank you for your contribution! Your PR looks good to me.

However, I need to check why the tests are failing before merging your changes. Thank you for patience!

**Comment by jlutz777** [comment]
Sounds great, @manekinekko. When I made the PR there were already failing tests, so hopefully it is unrelated. If it is something with my code, just let me know.

**Comment by vogloblinsky** [comment]
Thanks for the PR. I will check later if it breaks existing tests.

**Pull request merged**
